### ISSUE TITLE
All I get is Invalid client_id

### ISSUE THREAD

**Issue by Ashleyde42** [jbergler/hass-ttlock#100]
## Describe the bug

I have added the TTlock integration but the username and password always fail with an invalid client_id

I have tried the userid/password for the TTlock app where I created a project/account.

But then the integration says to user the login details from the TTlock app, so I am not sure why I created a project/account?

Anyway I also tried these but they fail as well.  For the useid I tried the nickname, the account and the email as the Login to TTLock just says login details so is not clear to me which one to use.  So I tried all three and all three fail.

I have also reset the password and tried the four userids and they all still fail.

Am I doing soemthing wrong?

Ash

## Diagnostic info

Please download the diagnostic info for tttlock from within Home Assistant and **attach** it to this ticket.
There are instructions on how to do this [here](https://www.home-assistant.io/integrations/diagnostics/)

**Comment by JoshKelleway** [comment]
stuck at the same place as well...

**Comment by Medar46** [comment]
Also I get the same status..Any ideas??


Update:
Delete From hidden .Storage file the TTlock folder and also an auth for TTlock resolve the problem.

**Comment by lsellens** [comment]
Also having this issue. Could not find any TTlock folder in .storage

**Comment by Medar46** [comment]
.storage/aplication_credentials
and delete it.

**Comment by jbergler** [comment]
Application Credentials are a core feature of home assistant (documented [here](https://www.home-assistant.io/integrations/application_credentials/))

You don't need to nuke the directory manually, instead you can selectively remove credentials from the UI.

**Comment by Ashleyde42** [comment]
Sorry but I was a bit busy the last couple of weeks.
This item is not closed.

I went to the applications credentials (top RHS ... of Settings screen and deleted the TTlock credentials like asdvised.

Now on setting spage 
Under Integrations I have no TTLOCK
Under devices i get TTLock but no services
Under Entities I get "TTL Update"
Under Helpers i get nothing

I am trying to get the services/features as described in
URL https://github.com/jbergler/hass-ttlock/blob/develop/README.md
Overview
This integration uses the TTLock Cloud to communicate with your lock. It supports the following features:

Locking and unlocking
Discovery of locks on startup
Real-time updates via a webhook (no periodic polling which wastes battery)
Additional sensors for battery, last operator + reason
Add new pass codes
Delete expired pass codes

So how do i get access to these features?
I am baffled.  I am not sure why i removed the credentials.

Can anyone assist.

Ash

**Comment by jbergler** [comment]
Hey Ash - the issue is for an invalid client id, which is out of scope for what I can support. The guidance I provided is to remove the invalid credentials that were entered when setting the integration up. This allows you to configure the integration again from scratch within home assistant.

If you're still having issues with invalid app credentials, please reach out to ttlock for help.
