### ISSUE TITLE
Unable to load ttlock

### ISSUE THREAD

**Issue by uswong** [jbergler/hass-ttlock#111]
## Describe the bug

Unable to load ttlock and the lock registered in ttlock was not made available in HomeAssistant.   The lock works fine using ttlock app.

This happened after I upgraded HA to 2024.5.1

![image](https://github.com/jbergler/hass-ttlock/assets/96530237/24431a7c-244f-4df3-8f67-c5fd238abe40)

### To Reproduce

I have deleted the integration and reconfigured the integration again. The authentication was successful and created configuration but the integration could not be loaded.  Restart HomeAssistant did not help.

![image](https://github.com/jbergler/hass-ttlock/assets/96530237/be848da9-276d-4d6f-989d-5c1b56c92c2a)

The error as follow"

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 4 May 2024 at 22:06:28 (1 occurrences)
Last logged: 4 May 2024 at 22:06:28

Error during setup of component ttlock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ttlock/__init__.py", line 53, in setup
    Services(hass).register()
  File "/config/custom_components/ttlock/services.py", line 77, in register
    self.hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'ttlock' calls async_register from a thread at custom_components/ttlock/services.py, line 77: self.hass.services.async_register(. Please report it to the author of the 'ttlock' custom integration.

### Expected behavior

To load successfully and able to control the locks registered in ttlock.

## Diagnostic info

No "Download diagnostic" option for me to download any diagnostic.   There is no "reload" option as well.

The options I have is as follow:

![image](https://github.com/jbergler/hass-ttlock/assets/96530237/86314114-932d-4eb9-8446-36139f4dfe98)

Please download the diagnostic info for tttlock from within Home Assistant and **attach** it to this ticket.
There are instructions on how to do this [here](https://www.home-assistant.io/integrations/diagnostics/)

**Comment by uswong** [comment]
Upgrade to v0.6.2 resolved the issue.  Thanks.

**Comment by jbergler** [comment]
Noting this is a dupe of #107
