### ISSUE TITLE
Lock unavailable since update to 2024.5.5

### ISSUE THREAD

**Issue by Wheemer** [jbergler/hass-ttlock#116]
My lock is unavailable within home assistant since upgrading to version 2024.5.5

I tried to look for logs but nothing is mentioned. I tried restarting however no difference.

Anyone else seeing this issue?

**Comment by jbergler** [comment]
Insufficient info provided, please follow the instructions in the issue template to provide debug logging.

**Comment by Wheemer** [comment]
[config_entry-ttlock-7dddddb38deb22af184e590040c46b30.json](https://github.com/user-attachments/files/15520290/config_entry-ttlock-7dddddb38deb22af184e590040c46b30.json)

**Comment by Wheemer** [comment]
For your information the issue template doesn't describe how to provide debug logging, it only describes how to provide device diagnostics.

Is it really productive for you to just close my issue instead of allowing me to post the diagnostics?

The integration has been working fine since the last time Home Assistant updated something that broke it.

**Comment by Wheemer** [comment]
I deleted and readded the integration and set it up again and now there is no lock present, even though setting it up was successful.
[config_entry-ttlock-4e33b8463d78465414e53da043edbde3.json](https://github.com/user-attachments/files/15522072/config_entry-ttlock-4e33b8463d78465414e53da043edbde3.json)

**Comment by Wheemer** [comment]
I have tried to figure out how to put ttlock in debug mode but I cannot figure it out. Might you be able to link me to something?

**Comment by jbergler** [comment]
Docs are here: https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging

Sorry if me closing the ticket was abrupt, I've been getting a bunch of issue reports lately without any meaningful info.
I've updated the issue template with better instructions (didn't realise it wasn't obvious), please feel free to open a new issue with the requested info.
