### ISSUE TITLE
How do I change webbooks?

### ISSUE THREAD

**Issue by Menz01** [jbergler/hass-ttlock#124]
I recently moved to a new domain. How do I change the webhook? I tried changing it in the app I created on the website via the directions but when edit the webhook it gives me an error when I change the domain

**Comment by Menz01** [comment]
figured it out

**Comment by mrahmadt** [comment]
Please share your solution

**Comment by jagssai** [comment]
I have the same problem and have tried everything I can think of but have not been able to solve it, please share how you solved it.
