### ISSUE TITLE
Slow status update 

### ISSUE THREAD

**Issue by mrahmadt** [jbergler/hass-ttlock#129]
Using webhook the door status update is slow

I know this is not hass-ttlock issue rather than slow push from ttlock platform to the webhook

My question, is there a way to pull the status from the lock directly instead of the api? (My lock is directly powered so I'm not worried about battery)

**Comment by jbergler** [comment]
There ttlock apis don’t allow for local access unless you wish to reimplement their Bluetooth protocol.

There is another project I remember seeing that tries to do this, but I don’t remember what it was called or how far they got.
