### ISSUE TITLE
The webhook url that the HA OS gives is invalid in the ttlock app managment website and i get this message ( Callback url test failed:java.io.lOException: Unexpected code Response{protocolshttp/1.1, code=403, message=Forbidden, url=http://**********.com/api/webhook/d8************************+++++**********}

### ISSUE THREAD

**Issue by vip4646** [jbergler/hass-ttlock#130]
The webhook url that the HA OS gives is invalid in the ttlock app management website and i get this message ( Callback url test failed:java.io.lOException: Unexpected code Response{protocolshttp/1.1, code=403, message=Forbidden, url=http://**********.com/api/webhook/d8************************+++++**********}

**Comment by jbergler** [comment]
You haven’t followed the instructions for reporting an issue so I can’t help.

The error says there’s a 403, so you probably need to check your server setup
