### ISSUE TITLE
The application does not accept the login.

### ISSUE THREAD

**Issue by Liipong** [jbergler/hass-ttlock#134]
Hello. The application does not accept the login. When I try to log in, it displays the message "invalid client_id". I tried to enter all possible combinations of usernames and passwords. I changed the password in the application (on the phone). But nothing helps! Maybe I'm doing something wrong? But I do everything according to the instructions: I use the username and password that I use to log in to the application on my phone. I tried to change the password and username in the application on the phone, but it is still impossible to log in from the TTLOCK integration! Please tell me, step by step, what needs to be done to activate the TTLock integration? Thank you.

**Comment by jbergler** [comment]
It doesn't sound like you followed the instructions in the README, please read them again and make sure you create the oauth app to have a valid client_id and client_secret.

To remove the existing credentials, see https://github.com/jbergler/hass-ttlock/issues/55#issuecomment-1610036292
