### ISSUE TITLE
webhook url?

### ISSUE THREAD

**Issue by cordvision** [jbergler/hass-ttlock#14]
According to the documentation: "Once the integration is working, go to System > Logs and find the ttlock webhook url"

Where is this located exactly and what does it look like? If I go to "System > Logs" I can choose from a list: HOME ASSISTANT CORE, SUPERVISOR, HOST, etc. 
Where do I find the webhook? I looked through all of those logs and couldn't find anything.

Thanks....
Michael

**Comment by jbergler** [comment]
Settings > System > Logs should have it? The url is `/config/logs` 

From there you can search for `ttlock` and press the "Load full logs" button

**Comment by cordvision** [comment]
Nothing shows up there relating to webhooks. This is the only entry I find  when searching for "ttlock" in the logs:

2023-04-13 00:35:36.393 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ttlock which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by jbergler** [comment]
Interesting, have you actually added the integration after installing it?
If that's the only message in the logs I would guess that you need to go to Settings > Integrations and add TTLock there first

**Comment by cordvision** [comment]
Yes, I have added it. I can actually already use it (I can unlock the lock via the Home Assistant Dashboard). However, no unlock events show up in the history at all. I thought this is because I haven't added the webhook url yet. Am I missing something?

**Comment by cordvision** [comment]
Here are two screenshots... Am I looking in the wrong place?
<img width="1048" alt="Screenshot 2023-04-13 at 03 49 59" src="https://user-images.githubusercontent.com/14810812/231626499-ce146c07-41a4-4e7b-898e-43f396f4cb95.png">
<img width="1819" alt="Screenshot 2023-04-13 at 03 50 27" src="https://user-images.githubusercontent.com/14810812/231626504-2ef264c5-349a-4322-ba07-830586eea79b.png">

**Comment by jlmpenedo** [comment]
I have the same dificult. No webhook url on logs, only this:

_This error originated from a custom integration.

Logger: custom_components.ttlock.api
Source: custom_components/ttlock/api.py:165
Integration: TTLock (documentation, issues)
First occurred: 22:55:36 (3 occurrences)
Last logged: 22:55:39

Failed to lock Fechad M302_abfa15: The function is not supported for this lock."_

I found some information on DEVICE INFORMATION - DOWLOAD DIAGNOSTICS, but it is  REDACTED
"webhook_url": "**REDACTED**"

**Comment by jbergler** [comment]
I guess the default log levels aren't what I thought they were.

I'll release a new version shortly that pops up a notification when the integration starts up if the webhook hasn't received data.

**Comment by jbergler** [comment]
Thanks for the feedback everyone, hopefully this sorts the issue out for you.

> Failed to lock Fechad M302_abfa15: The function is not supported for this lock."

@jlmpenedo If this persists, and you can unlock your lock through the app, please file a new issue

> I found some information on DEVICE INFORMATION - DOWLOAD DIAGNOSTICS, but it is REDACTED "webhook_url": "**REDACTED**"

This is intentional so that if you provide the diagnostic info in a ticket, sensitive info isn't exposed.
