### ISSUE TITLE
Integrate in own Software

### ISSUE THREAD

**Issue by bforpc** [jbergler/hass-ttlock#148]
Is it possible, to integrate  hass-ttlock in my own software. Im not using "Home Assistant"

Bfo

**Comment by bforpc** [comment]
nobody here, nothing?

**Comment by jbergler** [comment]
I don't know what you want. It's open source, fork the code.

**Comment by bforpc** [comment]
Why i should fork the code? The wheel is already builded.
I want to use the code in my own code. No more, no less. I'm not a python developer, only PHP and JS (amateur only).

Is this a problem for you???
