### ISSUE TITLE
step by step!

### ISSUE THREAD

**Issue by rondebon** [jbergler/hass-ttlock#150]
complete novice need help installing.
I have everything working up to getting the "webhook.url" notification. But what do I do with that? Also what do i put in the "callback.url" in open platform. Thanks for all your work. great stuff.

**Comment by GithubFred57** [comment]
I have just installed this integration and have exactly the same question. Should I replace the local HA address url produced in the notification tab with the external domain name address?

**Comment by e1w00db1ue5** [comment]
Hey,

I think, or at least this is what I have done :)

As the instructions say in the main page;

`Go back to the url from the first step and set the 'Callback URL' for your application`

Go to https://open.ttlock.com/manager, click on your app and in the middle is "CallBack URL", click edit and paste the webhook in.  

However I can't see any locks so...

J

**Comment by rondebon** [comment]
> Hey,
> 
> I think, or at least this is what I have done :)
> 
> As the instructions say in the main page;
> 
> `Go back to the url from the first step and set the 'Callback URL' for your application`
> 
> Go to https://open.ttlock.com/manager, click on your app and in the middle is "CallBack URL", click edit and paste the webhook in.
> 
> However I can't see any locks so...
> 
> J

Thats what I thought, but when i paste that in, there is a pause of some seconds, then I get this report "Callback url test failed:java.net.SocketTimeoutException : connect timed out"

**Comment by jbergler** [comment]
Hiya, the url needs to be accessible from the internet.

If it's generating a local url, it's because you haven't configured the external url for your instance in home assistant settings. If you go to Settings > System > Network and configure the "Home Assistant URL" section correctly.

To check if the url is accessible, you can use a website like https://www.yougetsignal.com/tools/open-ports/
If your url is "https://example.com/" you'd put example.com in the remote address field and set the port to 443 (for https)

**Comment by rondebon** [comment]
> Hiya, the url needs to be accessible from the internet.
> 
> If it's generating a local url, it's because you haven't configured the external url for your instance in home assistant settings. If you go to Settings > System > Network and configure the "Home Assistant URL" section correctly.
> 
> To check if the url is accessible, you can use a website like https://www.yougetsignal.com/tools/open-ports/ If your url is "https://example.com/" you'd put example.com in the remote address field and set the port to 443 (for https)

Got it now, Thanks.
