### ISSUE TITLE
My padlock doesn't go to locked status on Home Assistant

### ISSUE THREAD

**Issue by magusagnus** [jbergler/hass-ttlock#156]
## Describe the bug

I've bought a ttlock compatible padlock on [aliexpress](https://pt.aliexpress.com/item/1005006430116672.html): It works fine with G2 gateway. It was detected by your integration and added correctly to home assistant. I can unlock using unlock command and check who unlocked normally. The problem is that after padlock is unlocked the status is kept as unlocked and i can't use it again until i restart home assistant.

If the status is unlocked and you try to lock it by home assistant, an error is shown: 
`
Failed to execute the action lock/lock. API returned: {'errorcode': -4043, 'errmsg': 'The function is not supported for this lock.', 'description': 此锁不支持该操作 .}`

### Expected behavior

Is it possible to set the integration to 'automatically' changes status for this padlock to locked? when i do this on developers tools it kinda fixes the problem until i unlocked it again.

## Required information

Please provide:

- Debug logs reproducing the issue. For most issues, it is required to enable debug logging, and reload the extension so we capture the required information.
- The diagnostic info for ttlock.

**Comment by jbergler** [comment]
This is likely because you haven't enabled remote unlock, the readme has been updated with instructions on how to fix that. If that doesn't resolve your issue please either file a new bug with the requested information or start a discussion.

**Comment by magusagnus** [comment]
Hi @jbergler,

Thanks for your fast reply. I've had already activated the remote unlock, it's the only way to your integration find this padlock and add it to home assistant.

Using your integration i can unlock the padlock but the status unlocked keeps forever or until i restart the home assistant. while in this status (unlocked), i can't unlock again.

I tried to set manually the attribute from unlocked to locked using developers tools inside home assistant and it kinda fixes it until someone unlock again using home assistant.

I was thinking: Maybe the ttlock didn't implement a return information for padlock because it's a padlock instead of a door lock?. In that case could it be possible to implement a checkbox during configuration that if checked the integration could assume a locked status after a default time like 5 seconds?

I can send you screenshots or a small video showing the problem if you wish

Regards

Rodger

**Comment by mrde12** [comment]
I am experiencing the same issue. The Padlock cannot return to the locked status. Is there a way for the Padlock to have only the unlock function?
