### ISSUE TITLE
invalid client

### ISSUE THREAD

**Issue by minmd86** [jbergler/hass-ttlock#160]
I can't log in to my account "invalid client"

i am using locahot and duckdns

please help me

**Comment by jbergler** [comment]
see the readme
please help yourself

**Comment by minmd86** [comment]
Thank you, my problem is fixed
I deleted the config file and reconfigured id_oauth

Im using this key pattern
https://a.aliexpress.com/_oDky8IF

Now i have problem
it does not update the state of button
if i unlock on homeassistant it shows unlocked even though i locked it again
