### ISSUE TITLE
not getting records and lock is not updating when actions performed with the app

### ISSUE THREAD

**Issue by Menz01** [jbergler/hass-ttlock#45]
Hello, thank you for this integration it does sorta work and that is a good thing. now i just need to figure out what i am doing wrong. i have the app approved and setup in the TTLock Open Platform and have the client and secret codes. i have the integration setup and it shows in HA. i can unlock and lock from HA and thats where the working parts end. so here are the issues i am seeing and i am betting i messed something up:

1) as i said i can lock and unlock from HA and i can verify that locking and unlocking is working however i do not get any "last operator" or "last trigger" updates, they still say unknown

2) if i unlock the lock in the TTlock app itself and i look at the lock in HA it will show as still being locked and if i lock the lock in the TTlock app it will not show as locked in HA. the status just remains as it was in HA and i am still not getting any "last operator" or "last triggers" here either.... those values have remained "unknown" since integration

still despite these issue i am happy that this lock is in HA now

**Comment by jbergler** [comment]
Have you setup the webhook? 
If so, can you please enable debug logging and ensure you're receiving data from TTLock's cloud when you unlock the door?

```
logger:
  logs:
    homeassistant.components.webhook: debug
    custom_components.ttlock: debug
```

**Comment by Menz01** [comment]
so.... i fixed the issue. I did not setup the webhook properly and did not know how to determine the webhook address cause i cleared it from the notification before i knew that i needed it. luckily after a rester the webhook notification showed again and i added that address to the developer app and lo and behold the issue is resolved

**Comment by jbergler** [comment]
Awesome, glad to hear you got it working. If you run into other issues please report them!

**Comment by ghost** [comment]
I'm having the same issue - I have the lock working from HA, but if I unlock/lock the lock from the lock its self or the TTLock app it doesn't update in HA. I've taken the webhook address from the notifications and put it in the TTLock Open Platform under the callback URL, even removed and re-added the lock and got a new webhook URL. The Webhook URL HA is giving me is a local address (http:192.168.x.x:xxxx/api/webhook/xxxxx - redacted bits of it!), would this be my issue - giving the TTLock Open Platform a local address? If not, any other suggestion? I also can't seem to expose the lock from HA to HomeKit using the HomeKit Bridge integration within HA, but I was trying to get the webhook working first before I try to figure that out
