### ISSUE TITLE
Failed to call service lock/unlock. API returned: errorcode': -4043, 'errmsg': The function is not supported for this lock:

### ISSUE THREAD

**Issue by mabrochu-helpox** [jbergler/hass-ttlock#46]
## Describe the bug

I installed a new ttlock compatible lock, when I click on unlocked I have an error pop up.
Failed to call service lock/unlock. API returned: errorcode': -4043, 'errmsg': The function is not supported for this lock:

Unlock: give me the error and the popup and not unlock
Lock: No error, no popup and work after 3-4 seconds

![image](https://user-images.githubusercontent.com/69210101/235668330-65398dd6-1f6d-4634-9534-107c2561f2c5.png)

![image](https://user-images.githubusercontent.com/69210101/235676764-7aab9908-7997-4d0a-ba41-21405925ee7a.png)

SN9182-B_PV53

### To Reproduce

1. Go to entitie lock.porte_avant
2. Click on unlock
3. See error: Failed to call service lock/unlock. API returned: errorcode': -4043, 'errmsg': The function is not supported for this lock:

![image](https://user-images.githubusercontent.com/69210101/235668851-c52fe39d-23d3-4ce4-b816-59c94cfa6f68.png)

I have 2 ttlock locks, the lock_porte_arriere works well only the new lock.porte_avant does not work

## Diagnostic info

Please download the diagnostic info for tttlock from within Home Assistant and **attach** it to this ticket.
There are instructions on how to do this [here](https://www.home-assistant.io/integrations/diagnostics/)
[config_entry-ttlock-c5d792ed70a94b1feaf9c00fc90a7455.json (1).txt](https://github.com/jbergler/hass-ttlock/files/11373106/config_entry-ttlock-c5d792ed70a94b1feaf9c00fc90a7455.json.1.txt)

**Comment by mabrochu-helpox** [comment]
Everything is working i forget to enable remote unlock :)

**Comment by jbergler** [comment]
Glad to hear you sorted it out!
