### ISSUE TITLE
Simpled HF digital door lock -  May not be unlocked by HA

### ISSUE THREAD

**Issue by Dozer302** [jbergler/hass-ttlock#48]
Manufacturer: Simpled.uk
Model: HF
Gateway via AliExpress - works fine in the app for all controls.

Lock details:
SN9206-01_PV53
by TT Lock
Firmware: 6.0.7.210706
Hardware: 1.6

Added web hook to open.ttlocks   - throws this error:

Failed to call service lock/unlock. API returned: {'errcode': -4043, 'errmsg': 'The function is not supported for this lock.', 'description': '此锁不支持该操作。'}

The  Chinese actually means: 
This lock does not support the operation

so I can lock by not unlock via HA

**Comment by jbergler** [comment]
Hey @Dozer302 [looks](https://github.com/jbergler/hass-ttlock/issues/1#issuecomment-1546676445_) like you got this sorted out so I'll go ahead and close this!

> In the app I had not enabled "REMOTE UNLOCK" - lock now locking and unlocking remotely.

**Comment by uswong** [comment]
Hey, I have exactly the same issue as described by @Dozer302 above, may I know what is the solution?

**Comment by Dozer302** [comment]
In the app I had not enabled "REMOTE UNLOCK" - lock now locking and unlocking remotely.

enable REMOTE UNLOCK in the app settings.
