### ISSUE TITLE
Invalid Client: Login to TTLock

### ISSUE THREAD

**Issue by JagdDrache** [jbergler/hass-ttlock#55]
## Describe the bug

When i try to ender the Login to TTLOCK, it gave me Invalid Client error
I may have entered the wrong secret key initially, but i was unable to change anything about the secret key after multiple re-installation of the TTLOCK integration

Is there any way about it?

**Comment by jbergler** [comment]
Hey @JagdDrache - you can manage Application Credentials via the menu on the integration screen.
![image](https://github.com/jbergler/hass-ttlock/assets/698597/8e30ecfd-1acd-4108-930a-b1f526541dee)

If you need more info, the docs are here: https://www.home-assistant.io/integrations/application_credentials/
