### ISSUE TITLE
status up update

### ISSUE THREAD

**Issue by goldbe4804** [jbergler/hass-ttlock#64]
iam using a Laxre Fingerprint Smart Lock https://www.amazon.com/gp/product/B08J3STFH2/ref=ppx_yo_dt_b_asin_title_o09_s01?ie=UTF8&psc=1  seems to be working BUT HA is not updating. ex if i unlock the door -it unlocks - the lock will auto lock, But HA never updates to lock -is there something i can do/try to get it to update thank you jeff
HA  2023.7.2
just installed app :
SN9292-4V5_PV53
by TT Lock
Firmware: 6.4.11.220216
Hardware: 1.1

ps i had the account already setup with ttlock - i was using something ealse, but this seem to work better if i can get it to update in HA

![ttlock](https://github.com/jbergler/hass-ttlock/assets/56876314/235177bb-ce45-41b9-aacf-f82173f44bc2)

**Comment by jbergler** [comment]
Please enable debug logging for the integration, reload the integration, reproduce the error and then share the logs.

**Comment by goldbe4804** [comment]
hope i did this right!!  TY !
[home-assistant_ttlock_2023-07-16T20-57-27.408Z.log](https://github.com/jbergler/hass-ttlock/files/12065067/home-assistant_ttlock_2023-07-16T20-57-27.408Z.log)

**Comment by goldbe4804** [comment]
hope i did this right i stoped it a few sec after the lock -relocked  ty !
[home-assistant_ttlock_2023-07-16T21-04-06.242Z.log](https://github.com/jbergler/hass-ttlock/files/12065075/home-assistant_ttlock_2023-07-16T21-04-06.242Z.log)

**Comment by jbergler** [comment]
DEBUG info is in the logs so it looks good from that perspective.
I'm not seeing any webhooks coming through though. The URL in your logs has an internal IP, so maybe you need to change the url to something that is reachable across the internet. 

You should see log lines like this when the webhook is working:
```
2023-07-15 18:57:51.697 DEBUG (MainThread) [custom_components.ttlock] Got webhook data: <MultiDict(....)>
```

**Comment by goldbe4804** [comment]
Sorry can you please maybe- in steps tell me what I should try to do _ I can't belive the things i have done and figured out in HA but sometimes I need a little help thanks. 

Do u mean the address in the ttl web app

**Comment by jbergler** [comment]
Yeah, the url that gets generated in by ttlock doesn't know (without a cloud subscription) how you remotely access your home assistant instance.

Is your instance available on the internet? `http://192.168.1.35:8123/api/webhook/...` needs the ip address replaced with a public IP or something like a dynamic dns name before you put it in the ttlock portal.

**Comment by jbergler** [comment]
Although, re-reading your original message it sounds like maybe the webhooks are working, I just don't see them in the logs?

**Comment by jbergler** [comment]
I'll need debug logs while the door unlocks and auto-relocks. Could you also send me the diagnostic info for the integration ('Download Diagnostics' in the settings for the integration)

**Comment by goldbe4804** [comment]
1st ty for your help
yea no subscripion 
i understand what you are saying, but do not understand were my ip address would need to be changed (if it needs that)
so i reloaded - unlocked - waited a few sec after the lock locked and did the 2 downloads
ty !!!

[config_entry-ttlock-d823f3cf62b3f40ec0f4e12fa46df7e7.json.txt](https://github.com/jbergler/hass-ttlock/files/12065213/config_entry-ttlock-d823f3cf62b3f40ec0f4e12fa46df7e7.json.txt)
[home-assistant_ttlock_2023-07-16T22-10-16.633Z.log](https://github.com/jbergler/hass-ttlock/files/12065214/home-assistant_ttlock_2023-07-16T22-10-16.633Z.log)

**Comment by goldbe4804** [comment]
i see what you are talking about a webhook address of 192.168.1.35:8123
if this is the problem how can i fix it ??
ty jeff

**Comment by jbergler** [comment]
How do you access your instance remotely? I see a `no-ip.org` hostname in your logs, if that's the case you can change the IP in the url to match that same hostname+port you use for web access, that way TTLock's cloud can talk to your home assistant instance.

**Comment by goldbe4804** [comment]
Sorry this is were iam lost change it in what url ? & yes I use myha.no-ip.org:8123 jeff

**Comment by goldbe4804** [comment]
is this were you mean -if so i added my info -rebooted - reloaded - still not updating :( 
and now can see this in the file
2023-07-17 09:41:47.569 INFO (MainThread) [custom_components.ttlock] Webhook registered at http://??????.no-ip.org:8123/api/webhook/088fe6e7d46b27d6b281994a8e753a28a0a14c3f944b01b2efd7ce14b616d6ec
do i have to uninstall and reinstall the addon ???

![ha-ip](https://github.com/jbergler/hass-ttlock/assets/56876314/b36763f7-d8a1-4ed7-ae30-6cee1d91bf17)

**Comment by goldbe4804** [comment]
SO a few hours later- i rec'd the webhook info in the HA Notifications side bar --- in the ttlock online app i had the callback of https://??????ni-ip:8123 i replaced that with the new callback url found in the HA sidebar Notifications and now it works !!! TY so mush for you time and help

**Comment by goldbe4804** [comment]
question so if i use the ttlock app should HA react to the lock being locked or unlocked?
it's not a big deal at all for me just wondering as of now it does not react to the app   TY

**Comment by jbergler** [comment]
Remote actions (from Home Assistant, or the TTLock app) don't trigger webhooks, so there's no way for HA to know. My advice would be to limit the use of the app as much as you can.
