### ISSUE TITLE
reset the client_id

### ISSUE THREAD

**Issue by callejo79** [jbergler/hass-ttlock#66]
I try to integrate, but I write wrong client_id and secret_client I uninstalled the addon via hacs and the file from custom components was deteled but when I try to install again ism´t ask for the client_id and client_secret only ask for username and password and when I write it say invalid client_id 

how I can change it?

**Comment by jbergler** [comment]
The secrets are stored as application credentials. You need to remove them from the settings, the docs here should help https://www.home-assistant.io/integrations/application_credentials/
