### ISSUE TITLE
TTLock now "failed to set up," since HA 2023.9

### ISSUE THREAD

**Issue by FaberO42** [jbergler/hass-ttlock#69]
Firstly, major kudos for your most valued work on this plugin!!!

However sadly for me, TTLock now shows as "failed to set up," since HA 2023.9.

Repeated attempts to reload integration and/or restart Home Assistant, now consistently results in same error.

NOT a new installation - everything was clearly configured correctly, since working 100% okay for months, prior to this.

![TTLock](https://github.com/jbergler/hass-ttlock/assets/103919948/5fbecb11-daf0-4a30-9a88-64ed17c28d73)
[home-assistant_ttlock_2023-09-09T02-09-17.371Z.log](https://github.com/jbergler/hass-ttlock/files/12564407/home-assistant_ttlock_2023-09-09T02-09-17.371Z.log)

**Comment by acenuke** [comment]
Exact same issue with HA 2023.9.0 and 2023.9.1

**Comment by FaberO42** [comment]
> 

Concur. 😔

**Comment by jbergler** [comment]
Thanks for the report, I don't think this is related to the latest release, at least I can't reproduce this locally.
My suspicious is that theres an issue renewing the auth token. Could you try removing / re-adding the integration to force a new session? If that fixes it I can take another look at the error handling here.

**Comment by nedzalife** [comment]
Adding context that might be related? 
- Brand new HA OS + HACS install
- Newly approved, never used TTLocks OAuth creds
- Plugin asks for Client ID / Secret
- Plugin asks for TTLock account username & password
- Login failed error (have confirmed the login creds work to access OAuth info).

Perhaps TTLocks changed something in their CDN / Netscaler / DNS that's causing the settings within this plugin to no longer work?

Edit: ignore all of the above. My issues were completely PEBKAC. Thanks for the great add-on!

**Comment by acenuke** [comment]
I deleted the integration then added it back and it worked again. Not sure why that happened

**Comment by FaberO42** [comment]
> Thanks for the report, I don't think this is related to the latest release, at least I can't reproduce this locally. My suspicious is that theres an issue renewing the auth token. Could you try removing / re-adding the integration to force a new session? If that fixes it I can take another look at the error handling here.

Hi sir,
I can confirm that Deleting and (Re-)Adding the Integration does successfully resolve for me.

**Comment by jbergler** [comment]
I had tried in a previous release to add some automated credential expiration handling (since the sessions are only valid for a few months). If this happens again please let me know and I can take another look. In the meantime I'll mark this as closed.

Thanks for the reports!
