### ISSUE TITLE
How to modify a client in a configuration file.

### ISSUE THREAD

**Issue by Xuan797** [jbergler/hass-ttlock#73]
Hello development team:
I encountered a problem where I entered incorrect information when entering "client_id" and "client_secret" in the first step configuration interface of "TTlock". Causing me to display 'invalid_client' when entering the account and password for 'TTlock' in the second part. But you cannot go back to the previous step to modify 'client'. May I manually modify this information in the configuration file. May I know which configuration file I should modify. Or is there any other way to use it? I have uninstalled and installed it many times, but there is really no way.

**Comment by jbergler** [comment]
The secrets are stored as application credentials. You need to remove them from the settings, the docs here should help https://www.home-assistant.io/integrations/application_credentials/

**Comment by chinhdz123** [comment]
@jbergler hello, how can I config client_id, client_secret in a configuration file?
