### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by michal00111** [jbergler/hass-ttlock#88]
I have a problem with logging in to the integration, I enter the login and password as in the application and a message appears invalid client_id. I have created applications on an open platform.

**Comment by scrampker** [comment]
Same issue here -- can't seem to log in. I tried using my app email login, account nickname, and client_id from the dev portal (approved app.) No dice. Tried my password, and the secret.

**Comment by mikedrews** [comment]
Appears to be a problem with the TTLock portal itself.
I can't even login into the portal below.
https://euopen.ttlock.com/login

**Comment by michal00111** [comment]
> Appears to be a problem with the TTLock portal itself. I can't even login into the portal below. https://euopen.ttlock.com/login

I can log in normally.

**Comment by mikedrews** [comment]
> > Appears to be a problem with the TTLock portal itself. I can't even login into the portal below. https://euopen.ttlock.com/login
> 
> I can log in normally.

Does the integration give you an error when you try to reload it?

**Comment by oraichu** [comment]
I can login normally as well. But can't login with integration using same username and password.

**Comment by dwittrup1** [comment]
Same issue here. Any updates? I can login to both the App and API environment directly with no issues.

**Comment by dwittrup1** [comment]
Found the fix. Deleted the intgration then deleted the entity. This allowed me to reload the Client ID. Now connected.

**Comment by jbergler** [comment]
Glad you got it fixed.

**Comment by scrampker** [comment]
I don't think this problem is fixed for some of us. Mine still says invalid client_id just like the OP.

![image](https://github.com/jbergler/hass-ttlock/assets/15056860/c9adf939-3690-4422-9c13-9e89166c2290)

**Comment by jbergler** [comment]
Ok, can you try removing and re-adding the credentials to make sure that they are correct?
You can remove the credentials via the menu on the integrations page, per these docs: https://www.home-assistant.io/integrations/application_credentials/

**Comment by scrampker** [comment]
That seemed to do the trick. My lock was discovered from the cloud. Interesting. Maybe we can add a little note for people to try that if they have the same issue.
