### ISSUE TITLE
Unable to use the add and delete pass code functionality

### ISSUE THREAD

**Issue by purugupta99** [jbergler/hass-ttlock#90]
## Describe the bug

I am trying to access the add/delete passcode functionality via the ttlock device dashboard, such that I can set up the passcodes using the HA UI but I didn't see it over there to update/delete the passcodes. Can you help me with how I can use this service to update the passcodes pls? (I'm using the latest release version v0.6.1)

### To Reproduce

1. Go to TTLock dashboard from integrations
2. Click on the devices link to view all the devices under the integration
3. Select a device from the `/config/devices/dashboard` page
4. Under the controls and sensor widget, the service is not available

### Expected behavior

The service to add new passcodes should have been available under the controls settings

## Diagnostic info
[config_entry-ttlock-3c54564471c861d73666e707868b832a.json.txt](https://github.com/jbergler/hass-ttlock/files/13920660/config_entry-ttlock-3c54564471c861d73666e707868b832a.json.txt)

**Comment by purugupta99** [comment]
@PedroDelCargo, can you help here please? (I saw that you helped with the initial PR)

**Comment by PedroDelCargo** [comment]
> @PedroDelCargo, can you help here please? (I saw that you helped with the initial PR)

Hi,
There is no UI for this. It is a service that can be called with automations, scripts or from Development tools -> Services.
The service needs parameters to be set when you use it (Lock id, passcode, passcode name, start date/time and end date/time).
Personally, I use it to automate passcodes creation/deletion. I created automations that work fine. If you need help to create such an automation, let me know.
