### ISSUE TITLE
Callback URL Timeout Error

### ISSUE THREAD

**Issue by art804** [jbergler/hass-ttlock#95]
## Describe the bug

I have set up the integration and the TTLock API. I receive the callback URL as a HA system notification. However, this URL is a local URL (http://10.1.1.10:8123/api/webhook/longstringoftextandnumbers). When I enter this URL on the TTLock website as the Callback URL I get a Java Socket timeout error.

HA is set up in a Docker container and I don't have external web access set up.

What am I doing wrong?

### To Reproduce

As above

### Expected behavior

Not to receive an error. I'm sure I'm missing something basic but the GitHub readme doesn't specify what the callback URL is supposed to look like.

## Diagnostic info

N/A, issue with third party site

**Comment by jbergler** [comment]
The callback url needs to be accessible from the internet.
When you lock/unlock a door, the webhook comes from the ttlock cloud rather than from the local gateway.
